
markets_list =[
"id",
"time",
"Home",
"Away",
"Match Result 1",
"Double Chance X2",
"Match Result 2",
"Double Chance 1X",
"Match Result X",
"Double Chance 12",
"Corners: Result 1",
"Corners: Double Chance X2",
"Corners: Result 2",
"Corners: Double Chance 1X",
"Corners: Result X",
"Corners: Double Chance 12",
"Corners: Total Over 2.5",
"Corners: Total Under 2.5",
"Corners: Total Over 3",
"Corners: Total Under 3",
"Corners: Total Over 3.5",
"Corners: Total Under 3.5",
"Corners: Total Over 4",
"Corners: Total Under 4",
"Corners: Total Over 4.5",
"Corners: Total Under 4.5",
"Corners: Total Over 5",
"Corners: Total Under 5",
"Corners: Total Over 5.5",
"Corners: Total Under 5.5",
"Corners: Total Over 6",
"Corners: Total Under 6",
"Corners: Total Over 6.5",
"Corners: Total Under 6.5",
"Corners: Total Over 7",
"Corners: Total Under 7",
"Corners: Total Over 7.5",
"Corners: Total Under 7.5",
"Corners: Total Over 8",
"Corners: Total Under 8",
"Corners: Total Over 8.5",
"Corners: Total Under 8.5",
"Corners: Total Over 9",
"Corners: Total Under 9",
"Corners: Total Over 9.5",
"Corners: Total Under 9.5",
"Corners: Total Over 10",
"Corners: Total Under 10",
"Corners: Total Over 10.5",
"Corners: Total Under 10.5",
"Corners: Total Over 11",
"Corners: Total Under 11",
"Corners: Total Over 11.5",
"Corners: Total Under 11.5",
"Corners: Total Over 12",
"Corners: Total Under 12",
"Corners: Total Over 12.5",
"Corners: Total Under 12.5",
"Corners: Total Over 13",
"Corners: Total Under 13",
"Corners: Total Over 13.5",
"Corners: Total Under 13.5",
"Corners: Total Over 14",
"Corners: Total Under 14",
"Corners: Total Over 14.5",
"Corners: Total Under 14.5",
"Corners: Handicap 0.5 Home",
"Corners: Handicap -0.5 Home",
"Corners: Handicap 1 Home",
"Corners: Handicap -1 Home",
"Corners: Handicap 1.5 Home",
"Corners: Handicap -1.5 Home",
"Corners: Handicap 2 Home",
"Corners: Handicap -2 Home",
"Corners: Handicap 2.5 Home",
"Corners: Handicap -2.5 Home",
"Corners: Handicap 3 Home",
"Corners: Handicap -3 Home",
"Corners: Handicap 3.5 Home",
"Corners: Handicap -3.5 Home",
"Corners: Handicap 4 Home",
"Corners: Handicap -4 Home",
"Corners: Handicap 4.5 Home",
"Corners: Handicap -4.5 Home",
"Corners: Handicap 5 Home",
"Corners: Handicap -5 Home",
"Corners: Handicap 5.5 Home",
"Corners: Handicap -5.5 Home",
"Corners: Handicap 0.5 Away",
"Corners: Handicap -0.5 Away",
"Corners: Handicap 1 Away",
"Corners: Handicap -1 Away",
"Corners: Handicap 1.5 Away",
"Corners: Handicap -1.5 Away",
"Corners: Handicap 2 Away",
"Corners: Handicap -2 Away",
"Corners: Handicap 2.5 Away",
"Corners: Handicap -2.5 Away",
"Corners: Handicap 3 Away",
"Corners: Handicap -3 Away",
"Corners: Handicap 3.5 Away",
"Corners: Handicap -3.5 Away",
"Corners: Handicap 4 Away",
"Corners: Handicap -4 Away",
"Corners: Handicap 4.5 Away",
"Corners: Handicap -4.5 Away",
"Corners: Handicap 5 Away",
"Corners: Handicap -5 Away",
"Corners: Handicap 5.5 Away",
"Corners: Handicap -5.5 Away",
"Corners: Team 1 Total 0.5",
"Corners: Team 1 Total -0.5",
"Corners: Team 1 Total 1",
"Corners: Team 1 Total -1",
"Corners: Team 1 Total 1.5",
"Corners: Team 1 Total -1.5",
"Corners: Team 1 Total 2",
"Corners: Team 1 Total -2",
"Corners: Team 1 Total 2.5",
"Corners: Team 1 Total -2.5",
"Corners: Team 1 Total 3",
"Corners: Team 1 Total -3",
"Corners: Team 1 Total 3.5",
"Corners: Team 1 Total -3.5",
"Corners: Team 1 Total 4",
"Corners: Team 1 Total -4",
"Corners: Team 1 Total 4.5",
"Corners: Team 1 Total -4.5",
"Corners: Team 1 Total 5",
"Corners: Team 1 Total -5",
"Corners: Team 1 Total 5.5",
"Corners: Team 1 Total -5.5",
"Corners: Team 1 Total 6",
"Corners: Team 1 Total -6",
"Corners: Team 1 Total 6.5",
"Corners: Team 1 Total -6.5",
"Corners: Team 1 Total 7",
"Corners: Team 1 Total -7",
"Corners: Team 1 Total 7.5",
"Corners: Team 1 Total -7.5",
"Corners: Team 1 Total 8",
"Corners: Team 1 Total -8",
"Corners: Team 1 Total 8.5",
"Corners: Team 1 Total -8.5",
"Corners: Team 1 Total 9",
"Corners: Team 1 Total -9",
"Corners: Team 1 Total 9.5",
"Corners: Team 1 Total -9.5",
"Corners: Team 1 Total 10",
"Corners: Team 1 Total -10",
"Corners: Team 1 Total 10.5",
"Corners: Team 1 Total -10.5",
"Corners: Team 2 Total 0.5",
"Corners: Team 2 Total -0.5",
"Corners: Team 2 Total 1",
"Corners: Team 2 Total -1",
"Corners: Team 2 Total 1.5",
"Corners: Team 2 Total -1.5",
"Corners: Team 2 Total 2",
"Corners: Team 2 Total -2",
"Corners: Team 2 Total 2.5",
"Corners: Team 2 Total -2.5",
"Corners: Team 2 Total 3",
"Corners: Team 2 Total -3",
"Corners: Team 2 Total 3.5",
"Corners: Team 2 Total -3.5",
"Corners: Team 2 Total 4",
"Corners: Team 2 Total -4",
"Corners: Team 2 Total 4.5",
"Corners: Team 2 Total -4.5",
"Corners: Team 2 Total 5",
"Corners: Team 2 Total -5",
"Corners: Team 2 Total 5.5",
"Corners: Team 2 Total -5.5",
"Corners: Team 2 Total 6",
"Corners: Team 2 Total -6",
"Corners: Team 2 Total 6.5",
"Corners: Team 2 Total -6.5",
"Corners: Team 2 Total 7",
"Corners: Team 2 Total -7",
"Corners: Team 2 Total 7.5",
"Corners: Team 2 Total -7.5",
"Corners: Team 2 Total 8",
"Corners: Team 2 Total -8",
"Corners: Team 2 Total 8.5",
"Corners: Team 2 Total -8.5",
"Corners: Team 2 Total 9",
"Corners: Team 2 Total -9",
"Corners: Team 2 Total 9.5",
"Corners: Team 2 Total -9.5",
"Corners: Team 2 Total 10",
"Corners: Team 2 Total -10",
"Corners: Team 2 Total 10.5",
"Corners: Team 2 Total -10.5",
"Yellow Cards: Result 1",
"Yellow Cards: Double Chance X2",
"Yellow Cards: Result 2",
"Yellow Cards: Double Chance 1X",
"Yellow Cards: Result X",
"Yellow Cards: Double Chance 12",
"Yellow Cards: Total Over 1",
"Yellow Cards: Total Under 1",
"Yellow Cards: Total Over 1.5",
"Yellow Cards: Total Under 1.5",
"Yellow Cards: Total Over 2",
"Yellow Cards: Total Under 2",
"Yellow Cards: Total Over 2.5,",
"Yellow Cards: Total Under 2.5,",
"Yellow Cards: Total Over 3",
"Yellow Cards: Total Under 3",
"Yellow Cards: Total Over 3.5",
"Yellow Cards: Total Under 3.5",
"Yellow Cards: Total Over 4",
"Yellow Cards: Total Under 4",
"Yellow Cards: Total Over 4.5",
"Yellow Cards: Total Under 4.5",
"Yellow Cards: Total Over 5",
"Yellow Cards: Total Under 5",
"Yellow Cards: Total Over 5.5",
"Yellow Cards: Total Under 5.5",
"Yellow Cards: Total Over 6",
"Yellow Cards: Total Under 6",
"Yellow Cards: Total Over 6.5",
"Yellow Cards: Total Under 6.5",
"Yellow Cards: Total Over 7",
"Yellow Cards: Total Under 7",
"Yellow Cards: Total Over 7.5",
"Yellow Cards: Total Under 7.5",
"Yellow Cards: Total Over 8",
"Yellow Cards: Total Under 8",
"Yellow Cards: Total Over 8.5",
"Yellow Cards: Total Under 8.5",
"Yellow Cards: Total Over 9",
"Yellow Cards: Total Under 9",
"Yellow Cards: Total Over 9.5",
"Yellow Cards: Total Under 9.5",
"Yellow Cards: Total Over 10",
"Yellow Cards: Total Under 10",
"Yellow Cards: Total Over 10.5",
"Yellow Cards: Total Under 10.5",
"Yellow Cards: Handicap 0.5 Home",
"Yellow Cards: Handicap -0.5 Home",
"Yellow Cards: Handicap 1 Home",
"Yellow Cards: Handicap -1 Home",
"Yellow Cards: Handicap 1.5 Home",
"Yellow Cards: Handicap -1.5 Home",
"Yellow Cards: Handicap 2 Home",
"Yellow Cards: Handicap -2 Home",
"Yellow Cards: Handicap 2.5 Home",
"Yellow Cards: Handicap -2.5 Home",
"Yellow Cards: Handicap 3 Home",
"Yellow Cards: Handicap -3 Home",
"Yellow Cards: Handicap 3.5 Home",
"Yellow Cards: Handicap -3.5 Home",
"Yellow Cards: Handicap 4 Home",
"Yellow Cards: Handicap -4 Home",
"Yellow Cards: Handicap 4.5 Home",
"Yellow Cards: Handicap -4.5 Home",
"Yellow Cards: Handicap 5 Home",
"Yellow Cards: Handicap -5 Home",
"Yellow Cards: Handicap 5.5 Home",
"Yellow Cards: Handicap -5.5 Home",
"Yellow Cards: Handicap 0.5 Away",
"Yellow Cards: Handicap -0.5 Away",
"Yellow Cards: Handicap 1 Away",
"Yellow Cards: Handicap -1 Away",
"Yellow Cards: Handicap 1.5 Away",
"Yellow Cards: Handicap -1.5 Away",
"Yellow Cards: Handicap 2 Away",
"Yellow Cards: Handicap -2 Away",
"Yellow Cards: Handicap 2.5 Away",
"Yellow Cards: Handicap -2.5 Away",
"Yellow Cards: Handicap 3 Away",
"Yellow Cards: Handicap -3 Away",
"Yellow Cards: Handicap 3.5 Away",
"Yellow Cards: Handicap -3.5 Away",
"Yellow Cards: Handicap 4 Away",
"Yellow Cards: Handicap -4 Away",
"Yellow Cards: Handicap 4.5 Away",
"Yellow Cards: Handicap -4.5 Away",
"Yellow Cards: Handicap 5 Away",
"Yellow Cards: Handicap -5 Away",
"Yellow Cards: Handicap 5.5 Away",
"Yellow Cards: Handicap -5.5 Away",
"Yellow Cards: Team 1 Total Over 0.5",
"Yellow Cards: Team 1 Total Under 0.5",
"Yellow Cards: Team 1 Total Over 1",
"Yellow Cards: Team 1 Total Under 1",
"Yellow Cards: Team 1 Total Over 1.5",
"Yellow Cards: Team 1 Total Under 1.5",
"Yellow Cards: Team 1 Total Over 2",
"Yellow Cards: Team 1 Total Under 2",
"Yellow Cards: Team 1 Total Over 2.5",
"Yellow Cards: Team 1 Total Under 2.5",
"Yellow Cards: Team 1 Total Over 3",
"Yellow Cards: Team 1 Total Under 3",
"Yellow Cards: Team 1 Total Over 3.5",
"Yellow Cards: Team 1 Total Under 3.5",
"Yellow Cards: Team 1 Total Over 4",
"Yellow Cards: Team 1 Total Under 4",
"Yellow Cards: Team 1 Total Over 4.5",
"Yellow Cards: Team 1 Total Under 4.5",
"Yellow Cards: Team 1 Total Over 5",
"Yellow Cards: Team 1 Total Under 5",
"Yellow Cards: Team 1 Total Over 5.5",
"Yellow Cards: Team 1 Total Under 5.5",
"Yellow Cards: Team 1 Total Over 6",
"Yellow Cards: Team 1 Total Under 6",
"Yellow Cards: Team 1 Total Over 6.5",
"Yellow Cards: Team 1 Total Under 6.5",
"Yellow Cards: Team 2 Total Over 0.5",
"Yellow Cards: Team 2 Total Under 0.5",
"Yellow Cards: Team 2 Total Over 1",
"Yellow Cards: Team 2 Total Under 1",
"Yellow Cards: Team 2 Total Over 1.5",
"Yellow Cards: Team 2 Total Under 1.5",
"Yellow Cards: Team 2 Total Over 2",
"Yellow Cards: Team 2 Total Under 2",
"Yellow Cards: Team 2 Total Over 2.5",
"Yellow Cards: Team 2 Total Under 2.5",
"Yellow Cards: Team 2 Total Over 3",
"Yellow Cards: Team 2 Total Under 3",
"Yellow Cards: Team 2 Total Over 3.5",
"Yellow Cards: Team 2 Total Under 3.5",
"Yellow Cards: Team 2 Total Over 4",
"Yellow Cards: Team 2 Total Under 4",
"Yellow Cards: Team 2 Total Over 4.5",
"Yellow Cards: Team 2 Total Under 4.5",
"Yellow Cards: Team 2 Total Over 5",
"Yellow Cards: Team 2 Total Under 5",
"Yellow Cards: Team 2 Total Over 5.5",
"Yellow Cards: Team 2 Total Under 5.5",
"Yellow Cards: Team 2 Total Over 6",
"Yellow Cards: Team 2 Total Under 6",
"Yellow Cards: Team 2 Total Over 6.5",
"Yellow Cards: Team 2 Total Under 6.5",
"Offsides: Result 1",
"Offsides: Double Chance X2",
"Offsides: Result 2",
"Offsides: Double Chance 1X",
"Offsides: Result X",
"Offsides: Double Chance 12",
"Offsides: Total Over 0.5",
"Offsides: Total Under 0.5",
"Offsides: Total Over 1",
"Offsides: Total Under 1",
"Offsides: Total Over 1.5",
"Offsides: Total Under 1.5",
"Offsides: Total Over 2",
"Offsides: Total Under 2",
"Offsides: Total Over 2.5",
"Offsides: Total Under 2.5",
"Offsides: Total Over 3",
"Offsides: Total Under 3",
"Offsides: Total Over 3.5",
"Offsides: Total Under 3.5",
"Offsides: Total Over 4",
"Offsides: Total Under 4",
"Offsides: Total Over 4.5",
"Offsides: Total Under 4.5",
"Offsides: Total Over 5",
"Offsides: Total Under 5",
"Offsides: Total Over 5.5",
"Offsides: Total Under 5.5",
"Offsides: Total Over 6",
"Offsides: Total Under 6",
"Offsides: Total Over 6.5",
"Offsides: Total Under 6.5",
"Offsides: Total Over 7",
"Offsides: Total Under 7",
"Offsides: Total Over 7.5",
"Offsides: Total Under 7.5",
"Offsides: Total Over 8",
"Offsides: Total Under 8",
"Offsides: Total Over 8.5",
"Offsides: Total Under 8.5",
"Offsides: Total Over 9",
"Offsides: Total Under 9",
"Offsides: Total Over 9.5",
"Offsides: Total Under 9.5",
"Offsides: Handicap 0.5 Home",
"Offsides: Handicap -0.5 Home",
"Offsides: Handicap 1 Home",
"Offsides: Handicap -1 Home",
"Offsides: Handicap 1.5 Home",
"Offsides: Handicap -1.5 Home",
"Offsides: Handicap 2 Home",
"Offsides: Handicap -2 Home",
"Offsides: Handicap 2.5 Home",
"Offsides: Handicap -2.5 Home",
"Offsides: Handicap 3 Home",
"Offsides: Handicap -3 Home",
"Offsides: Handicap 3.5 Home",
"Offsides: Handicap -3.5 Home",
"Offsides: Handicap 4 Home",
"Offsides: Handicap -4 Home",
"Offsides: Handicap 4.5 Home",
"Offsides: Handicap -4.5 Home",
"Offsides: Handicap 5 Home",
"Offsides: Handicap -5 Home",
"Offsides: Handicap 5.5 Home",
"Offsides: Handicap -5.5 Home",
"Offsides: Handicap 0.5 Away",
"Offsides: Handicap -0.5 Away",
"Offsides: Handicap 1 Away",
"Offsides: Handicap -1 Away",
"Offsides: Handicap 1.5 Away",
"Offsides: Handicap -1.5 Away",
"Offsides: Handicap 2 Away",
"Offsides: Handicap -2 Away",
"Offsides: Handicap 2.5 Away",
"Offsides: Handicap -2.5 Away",
"Offsides: Handicap 3 Away",
"Offsides: Handicap -3 Away",
"Offsides: Handicap 3.5 Away",
"Offsides: Handicap -3.5 Away",
"Offsides: Handicap 4 Away",
"Offsides: Handicap -4 Away",
"Offsides: Handicap 4.5 Away",
"Offsides: Handicap -4.5 Away",
"Offsides: Handicap 5 Away",
"Offsides: Handicap -5 Away",
"Offsides: Handicap 5.5 Away",
"Offsides: Handicap -5.5 Away",
"Offsides: Team 1 Total 0.5",
"Offsides: Team 1 Total Under 0.5",
"Offsides: Team 1 Total Over 1",
"Offsides: Team 1 Total Under 1 ",
"Offsides: Team 1 Total 1.5",
"Offsides: Team 1 Total Under 1.5",
"Offsides: Team 1 Total Over 2",
"Offsides: Team 1 Total Under 2 ",
"Offsides: Team 1 Total 2.5",
"Offsides: Team 1 Total Under 2.5",
"Offsides: Team 1 Total Over 3",
"Offsides: Team 1 Total Under 3 ",
"Offsides: Team 1 Total 3.5",
"Offsides: Team 1 Total Under 3.5",
"Offsides: Team 1 Total Over 4",
"Offsides: Team 1 Total Under 4 ",
"Offsides: Team 1 Total 4.5",
"Offsides: Team 1 Total Under 4.5",
"Offsides: Team 1 Total Over 5",
"Offsides: Team 1 Total Under 5 ",
"Offsides: Team 1 Total 5.5",
"Offsides: Team 1 Total Under 5.5",
"Offsides: Team 1 Total Over 6",
"Offsides: Team 1 Total Under 6 ",
"Offsides: Team 1 Total 6.5",
"Offsides: Team 1 Total Under 6.5",
"Offsides: Team 2 Total Over 0.5",
"Offsides: Team 2 Total Under 0.5",
"Offsides: Team 2 Total Over 1",
"Offsides: Team 2 Total Under 1 ",
"Offsides: Team 2 Total Over 1.5",
"Offsides: Team 2 Total Under 1.5",
"Offsides: Team 2 Total Over 2",
"Offsides: Team 2 Total Under 2 ",
"Offsides: Team 2 Total Over 2.5",
"Offsides: Team 2 Total Under 2.5",
"Offsides: Team 2 Total Over 3",
"Offsides: Team 2 Total Under 3 ",
"Offsides: Team 2 Total Over 3.5",
"Offsides: Team 2 Total Under 3.5",
"Offsides: Team 2 Total Over 4",
"Offsides: Team 2 Total Under 4 ",
"Offsides: Team 2 Total Over 4.5",
"Offsides: Team 2 Total Under 4.5",
"Offsides: Team 2 Total Over 5",
"Offsides: Team 2 Total Under 5 ",
"Offsides: Team 2 Total Over 5.5",
"Offsides: Team 2 Total Under 5.5",
"Offsides: Team 2 Total Over 6",
"Offsides: Team 2 Total Under 6 ",
"Offsides: Team 2 Total Over 6.5",
"Offsides: Team 2 Total Under 6.5"]
